name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches: [main, feature/test]
  pull_request:
    branches: [main, feature/test]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.12.1]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: ğŸ§ install modules
        run: yarn install
        if: always()
      - name: ğŸ’¡ build production project
        run: yarn build:prod
        if: always()
      # - name: ğŸ” linting typescript
      #   run: yarn lint:ts
      # - name: ğŸ” linting scss
      #   if: always()
      #   run: yarn lint:scss
      # - name: ğŸ” unit testing
      #   if: always()
      #   run: yarn test:unit
      - name: ğŸ’¡ build storybook
        if: always()
        run: yarn sb:build
      - name: ğŸ–¥ï¸ visual regression testing
        run: yarn test:ui:ci
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  #     - name: unit testing
  #       run: yarn test:unit

  # Explore-GitHub-Actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
  #     - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  #     - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
  #     - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
  #     - name: List files in the repository
  #       run: |
  #         ls ${{ github.workspace }}
  #     - run: echo "ğŸ This job's status is ${{ job.status }}."
